[Icon Theme]
Name=ahoka-light
Inherits=
Comment=ahoka's icon theme based off Faience Next Generation (Dark)
DesktopDefault=48
ToolbarDefault=16
ToolbarSizes=16,22,32,48
MainToolbarDefault=16
MainToolbarSizes=16,22,32,48
PanelDefault=22
PanelSizes=16,22,32,48,64,128,256
Directories=16x16,48x48,scalable,


[16x16]
Size=16
Type=Fixed

[48x48]
Size=48
Type=Fixed

[scalable]
Size=16
MinSize=8
MaxSize=512
Type=Scalable
